# Generated by Django 4.0.4 on 2022-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_phone_name_alter_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='phone',
            name='lastname',
            field=models.CharField(default='Peter', max_length=20),
        ),
    ]
